remote_theme: pointbar/minima
author: Bénédicte Lambert
email: contact@benedictelambert.com
description : Afficher des recettes de cuisine en utilisant des contenus en markdown et un générateur de site jekyll pour la mise en page
